# Generated by Django 4.1.6 on 2023-02-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
